version: "3.8"
services:
  dockovpn:
    image: alekslitvinenk/openvpn
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
    environment:
      HOST_ADDR: ${HOST_ADDR} 
    volumes:
      - ./_data/openvpn_conf:/doc/Dockovpn

  cwatchtower:
    image: containrrr/watchtower
    mem_limit: 512m
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  sync_server:
    image: y2khub/sync_server
    mem_limit: 512m
    volumes:
      - $PWD/_data/sync_server:/app/app/__data

  mongodb:
    hostname: mongodb
    image: mongo:4.4.3-bionic
    mem_limit: 512m
    volumes:
      - $PWD/_data/mongodb:/data/db

  nginx:
    image: y2khub/reverse-proxy
    mem_limit: 512m
    depends_on:
      - sync_server
      - jr
      - remotecache
    ports:
      - 80:80

  # haproxy:
  #   image: haproxy:2.5.5-alpine3.15
  #   mem_limit: 512m
  #   depends_on:
  #     - sync_server
  #     - jr
  #     - remotecache
  #   ports:
  #     - 80:80
  #   volumes:
  #     - $PWD/_data/haproxy:/usr/local/etc/haproxy:ro

  spectator:
    image: y2khub/spectator
    mem_limit: 512m
    depends_on:
      - mongodb
    environment:
      - SPECTATOR_BOT_TOKEN=${SPECTATOR_BOT_TOKEN}
    volumes:
      - $PWD/_data/spectator:/app/__data

  remotecache:
    image: y2khub/remotecache
    mem_limit: 512m
    volumes:
      - $PWD/_data/remote-cache:/app/cache

  jr:
    mem_limit: 512m
    image: y2khub/jr

  trykt_bot:
    image: y2khub/tryktbot
    mem_limit: 512m
    environment:
      - TELEGRAM_TOKEN=${TRYKTBOT_TELEGRAM_TOKEN}

  watchcat_bot:
    image: y2khub/watchcat-bot
    mem_limit: 512m
    command: /app/data/data.json
    volumes:
      - $PWD/_data/watchcat_bot:/app/data
    environment:
      - TELEGRAM_TOKEN=${WATCHCATBOT_TELEGRAM_TOKEN}

  relaxcats_bot:
    image: y2khub/relaxcats_bot
    mem_limit: 512m
    environment:
      - TELEGRAM_TOKEN=${RELAXCATSBOT_TELEGRAM_TOKEN}
      - GIPHY_API_KEY=${RELAXCATSBOT_GIPHY_API_KEY}

  docker_bot:
    image: y2khub/docker-bot
    mem_limit: 512m
    command: "${DOCKERBOT_TELEGRAM_TOKEN} ${DOCKERBOT_OWNER}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  delete_messages_bot:
    image: y2khub/delete_messages_bot
    mem_limit: 512m
    environment:
      - TELEGRAM_TOKEN=${DELETE_SERVICE_MESSAGE_BOT_TELEGRAM}
