version: "3.8"
services:
  sync_server:
    image: y2khub/sync_server
    mem_limit: 512m
    volumes:
      - /root/sync:/app/app/__data

#   nuget_bot:
#     image: y2khub/nuget-bot
#     mem_limit: 512m
#     command: "${MYGETBOT_TOKEN} ${MYGETBOT_TELEGRAM_TOKEN} ${MYGETBOT_GITHUB_TOKEN}"
#     volumes:
#       - /root/nuget-bot:/app/__data

  cwatchtower:
    image: containrrr/watchtower
    mem_limit: 512m
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  haproxy:
    image: haproxy:2.3.2-alpine
    mem_limit: 512m
    ports:
      - 80:80
    volumes:
      - /root/haproxy:/usr/local/etc/haproxy:ro

  mongodb:
    image: mongo:4.4.3-bionic
    mem_limit: 512m
    volumes:
      - /root/mongodb:/data/db

  spectator:
    image: y2khub/spectator
    mem_limit: 512m
    depends_on:
      - mongodb
    command: /data/settings.yaml
    volumes:
      - /root/spectator:/data

  remotecache:
    image: y2khub/remotecache
    mem_limit: 512m
    volumes:
      - /root/remote-cache:/app/cache

  jr:
    mem_limit: 512m
    image: y2khub/jr

  trykt_bot:
    image: y2khub/tryktbot
    mem_limit: 512m
    environment:
      - TELEGRAM_TOKEN=${TRYKTBOT_TELEGRAM_TOKEN}

#   fsdn_bot:
#     image: y2khub/fsdn_bot
#     mem_limit: 512m
#     environment:
#       - TELEGRAM_TOKEN=${FSDNBOT_TELEGRAM_TOKEN}

  watchcat_bot:
    image: y2khub/watchcat-bot
    mem_limit: 512m
    command: /app/data/data.json
    volumes:
      - /root/watchcat_bot:/app/data
    environment:
      - TELEGRAM_TOKEN=${WATCHCATBOT_TELEGRAM_TOKEN}

  relaxcats_bot:
    image: y2khub/relaxcats_bot
    mem_limit: 512m
    environment:
      - TELEGRAM_TOKEN=${RELAXCATSBOT_TELEGRAM_TOKEN}
      - GIPHY_API_KEY=${RELAXCATSBOT_GIPHY_API_KEY}

  docker_bot:
    image: y2khub/docker-bot
    mem_limit: 512m
    command: "${DOCKERBOT_TELEGRAM_TOKEN} ${DOCKERBOT_OWNER}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  delete_messages_bot:
    image: y2khub/delete_messages_bot
    mem_limit: 512m
    environment:
      - TELEGRAM_TOKEN=${DELETE_SERVICE_MESSAGE_BOT_TELEGRAM}
