version: "3.8"

volumes:
  gpbuilder_shared:
#     external: true

services:
  github_pages_builder:
    image: y2khub/github_pages_builder
    mem_limit: 512m
    privileged: true
    environment:
      - GPB_TOKEN=$GPB_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gpbuilder_shared:/app/__build__

#   torrents_bot:
#     image: y2khub/torrents_bot
#     mem_limit: 512m
#     environment:
#       - CONFIG=$TORRENTS_BOT_CONFIG

  # vpn:
  #   image: hwdsl2/ipsec-vpn-server
  #   ports:
  #     - "500:500/udp"
  #     - "4500:4500/udp"
  #   privileged: true
  #   container_name: ipsec_vpn_server
  #   volumes:
  #     - $PWD/_data/ikev2_vpn_data:/etc/ipsec.d
  #     - /lib/modules:/lib/modules:ro
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=false"

  cwatchtower:
    image: containrrr/watchtower
    mem_limit: 512m
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # sync_server:
  #   image: y2khub/sync_server
  #   mem_limit: 512m
  #   volumes:
  #     - $PWD/_data/sync_server:/app/app/__data

  reverse_proxy:
    image: y2khub/reverse-proxy
    mem_limit: 512m
    depends_on:
      - sync_server
      - jr
      - remotecache
    ports:
      - 443:443
    volumes:
      - $PWD/_data/reverse_proxy:/etc/haproxy/ssl/

  # spectator:
  #   image: y2khub/spectator
  #   mem_limit: 512m
  #   environment:
  #     - SPECTATOR_BOT_TOKEN=${SPECTATOR_BOT_TOKEN}
  #   volumes:
  #     - $PWD/_data/spectator:/app/__data

  remotecache:
    image: y2khub/remotecache
    mem_limit: 512m
    volumes:
      - $PWD/_data/remote-cache:/app/cache

  jr:
    mem_limit: 512m
    image: y2khub/jr

#   trykt_bot:
#     image: y2khub/tryktbot
#     mem_limit: 512m
#     environment:
#       - TELEGRAM_TOKEN=${TRYKTBOT_TELEGRAM_TOKEN}

#   watchcat_bot:
#     image: y2khub/watchcat-bot
#     mem_limit: 512m
#     command: /app/data/data.json
#     volumes:
#       - $PWD/_data/watchcat_bot:/app/data
#     environment:
#       - TELEGRAM_TOKEN=${WATCHCATBOT_TELEGRAM_TOKEN}

  # relaxcats_bot:
  #   image: y2khub/relaxcats_bot
  #   mem_limit: 512m
  #   environment:
  #     - TELEGRAM_TOKEN=${RELAXCATSBOT_TELEGRAM_TOKEN}
  #     - GIPHY_API_KEY=${RELAXCATSBOT_GIPHY_API_KEY}

  docker_bot:
    image: y2khub/docker-bot
    mem_limit: 512m
    command: "${DOCKERBOT_TELEGRAM_TOKEN} ${DOCKERBOT_OWNER} ${DOCKERBOT_ORIGIN}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#   delete_messages_bot:
#     image: y2khub/delete_messages_bot
#     mem_limit: 512m
#     environment:
#       - TELEGRAM_TOKEN=${DELETE_SERVICE_MESSAGE_BOT_TELEGRAM}
