version: "3.8"
services:
  nuget_bot:
    image: y2khub/nuget-bot
    command: "${MYGETBOT_TOKEN} ${MYGETBOT_TELEGRAM_TOKEN} ${MYGETBOT_GITHUB_TOKEN}"

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  haproxy:
    image: haproxy:2.3.2-alpine
    ports:
      - 80:80
    volumes:
      - /root/haproxy:/usr/local/etc/haproxy:ro

  mongodb:
    image: mongo:4.4.3-bionic
    volumes:
      - /root/mongodb:/data/db

  spectator:
    image: y2khub/spectator
    depends_on:
      - mongodb
    command: /data/settings.yaml
    volumes:
      - /root/spectator:/data

  remotecache:
    image: y2khub/remotecache
    volumes:
      - /root/remote-cache:/app/cache

  jr:
    image: y2khub/jr

  trykt_bot:
    image: y2khub/tryktbot
    environment:
      - TELEGRAM_TOKEN=${TRYKTBOT_TELEGRAM_TOKEN}

  fsdn_bot:
    image: y2khub/fsdn_bot
    environment:
      - TELEGRAM_TOKEN=${FSDNBOT_TELEGRAM_TOKEN}

  watchcat_bot:
    image: y2khub/watchcat-bot
    command: /app/data/data.json
    volumes:
      - /root/watchcat_bot:/app/data
    environment:
      - TELEGRAM_TOKEN=${WATCHCATBOT_TELEGRAM_TOKEN}

  relaxcats_bot:
    image: y2khub/relaxcats_bot
    environment:
      - TELEGRAM_TOKEN=${RELAXCATSBOT_TELEGRAM_TOKEN}
      - GIPHY_API_KEY=${RELAXCATSBOT_GIPHY_API_KEY}

  docker_bot:
    image: y2khub/docker-bot
    command: "${DOCKERBOT_TELEGRAM_TOKEN} ${DOCKERBOT_OWNER}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
