version: "3.8"

services:
  trykt_bot:
    image: y2khub/tryktbot
    environment:
      - TELEGRAM_TOKEN=${TRYKTBOT_TELEGRAM_TOKEN}

  fsdn_bot:
    image: y2khub/fsdn_bot
    environment:
      - TELEGRAM_TOKEN=${FSDNBOT_TELEGRAM_TOKEN}

  watchcat_bot:
    image: y2khub/watchcat-bot
    command: /app/data/data.json
    volumes:
      - /root/watchcat_bot:/app/data
    environment:
      - TELEGRAM_TOKEN=${WATCHCATBOT_TELEGRAM_TOKEN}

  relaxcats_bot:
    image: y2khub/relaxcats_bot
    environment:
      - TELEGRAM_TOKEN=${RELAXCATSBOT_TELEGRAM_TOKEN}
      - GIPHY_API_KEY=${RELAXCATSBOT_GIPHY_API_KEY}

  docker_bot:
    image: y2khub/docker-bot
    command: "${DOCKERBOT_TELEGRAM_TOKEN} ${DOCKERBOT_OWNER}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
